### ISSUE TITLE
Cython compile error when building from source

### ISSUE THREAD

**Issue by cuom1999** [DMOJ/judge-server#1134]
I clone the latest code and build from source with these commands:
```
$ git clone --recursive https://github.com/DMOJ/judge-server.git
$ cd judge-server
$ pip install -e .
```
It fails to build due to compile errors. I tested with Ubuntu and WSL2 (both used to work). Full log:

```
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/cuom1999/tmp/judge-server
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [81 lines of output]

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          def abi(self):
              return self.thisptr.abi()

          def on_return(self, callback):
              self.on_return_callback[self.tid] = callback
              self.thisptr.on_return(pt_syscall_return_handler, <void*>self)
                                     ^
      ------------------------------------------------------------

      dmoj/cptbox/_cptbox.pyx:404:31: Cannot assign type 'void (void *, pid_t, int) except * nogil' to 'pt_syscall_return_callback'

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self._cpu_affinity_mask = 0
              self._init_nvcsw = self._init_nivcsw = 0

              self.debugger = self.create_debugger()
              self.process = new pt_process(self.debugger.thisptr)
              self.process.set_callback(pt_syscall_handler, <void*>self)
                                        ^
      ------------------------------------------------------------

      dmoj/cptbox/_cptbox.pyx:438:34: Cannot assign type 'int (void *, int) except? -1 nogil' to 'pt_handler_callback'

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self._init_nvcsw = self._init_nivcsw = 0

              self.debugger = self.create_debugger()
              self.process = new pt_process(self.debugger.thisptr)
              self.process.set_callback(pt_syscall_handler, <void*>self)
              self.process.set_event_proc(pt_event_handler, <void*>self)
                                          ^
      ------------------------------------------------------------

      dmoj/cptbox/_cptbox.pyx:439:36: Cannot assign type 'int (void *, int, unsigned long) except? -1 nogil' to 'pt_event_callback'

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                          PyErr_NoMemory()

                      for i in range(MAX_SYSCALL):
                          config.seccomp_handlers[i] = handlers[i]

                  if self.process.spawn(pt_child, &config):
                                        ^
      ------------------------------------------------------------

      dmoj/cptbox/_cptbox.pyx:522:34: Cannot assign type 'int (void *) except? -1 nogil' to 'pt_fork_handler'
      Compiling /home/cuom1999/tmp/judge-server/dmoj/cptbox/_cptbox.pyx because it changed.
      [1/1] Cythonizing /home/cuom1999/tmp/judge-server/dmoj/cptbox/_cptbox.pyx
      Traceback (most recent call last):
        File "/home/cuom1999/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/cuom1999/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/cuom1999/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-iion7k9h/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 450, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-iion7k9h/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-iion7k9h/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-iion7k9h/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-iion7k9h/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 177, in <module>
        File "/tmp/pip-build-env-iion7k9h/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-iion7k9h/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: /home/cuom1999/tmp/judge-server/dmoj/cptbox/_cptbox.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by cuom1999** [comment]
Probably related to this: https://github.com/cython/cython/issues/5498
I changed the definition code in `_cptbox.pyx` to below and it works.
```
cdef int pt_child(void *context) noexcept nogil:
    cdef child_config *config = <child_config*> context
    return cptbox_child_run(config)

cdef int pt_syscall_handler(void *context, int syscall) noexcept nogil:
    return (<Process>context)._syscall_handler(syscall)

cdef void pt_syscall_return_handler(void *context, pid_t pid, int syscall) noexcept with gil:
    (<Debugger>context)._on_return(pid, syscall)

cdef int pt_event_handler(void *context, int event, unsigned long param) noexcept nogil:
    return (<Process>context)._event_handler(event, param)
```
