### ISSUE TITLE
How can I look into logs of testing?

### ISSUE THREAD

**Issue by xDololow** [DMOJ/judge-server#1188]
Because I get WA when I shouldn't.

**Comment by Riolku** [comment]
I think you can see the docker logs... not sure if the statuses of submissions are put there. Otherwise, you can use the dmoj cli to manually kick off a submission, I think?

If you mean on the main DMOJ instance - you can't, generally. You can join the DMOJ discord and ask for help in the `help` channel.

**Comment by xDololow** [comment]
I only get logs like this, but i want to see all inputs and outputs to see why it doesn't work
```
INFO 2024-11-20 05:40:35,828 4318 judge Start grading cypher/48 in PY3...
INFO 2024-11-20 05:40:35,862 4318 packet Accept submission: 48: executor: PY3, code: cypher
INFO 2024-11-20 05:40:36,152 4318 judge Test case  1 WA [0.043s (0.063s wall) | 9260kb | 368 switches (9 involuntary)]
INFO 2024-11-20 05:40:36,154 4318 judge Done grading cypher/48.
```

**Comment by Riolku** [comment]
Inputs and outputs are generally massive... but you can either a) look at the zip file and manually run the code and compare or b) use the generator to generate the input and output. I dont think we have provisions in place to show full I/O

**Comment by xDololow** [comment]
> look at the zip file and manually run the code and compare

Well, I've already run it and it's fine locally. But in DMOJ it's all WA except when I choose line-by-line checker it returns as 1 correct answer (basically first line).

**Comment by xDololow** [comment]
ok I ran judger in debug mode and i got that output on judging:
```
NFO 2024-11-20 09:14:37,520 12538 judge Start grading cypher/51 in PY3...
INFO 2024-11-20 09:14:37,530 12538 packet Accept submission: 51: executor: PY3, code: cypher
DEBUG 2024-11-20 09:14:37,532 12538 inotify_buffer in-event <InotifyEvent: src_path=b'/home/webadmin/dmoj-docker/dmoj/problems', wd=1, mask=IN_ISDIR|IN_OPEN, cookie=0, name=''>
DEBUG 2024-11-20 09:14:37,533 12538 inotify_buffer in-event <InotifyEvent: src_path=b'/home/webadmin/dmoj-docker/dmoj/problems', wd=1, mask=IN_CLOSE_NOWRITE|IN_ISDIR, cookie=0, name=''>
DEBUG 2024-11-20 09:14:37,535 12538 inotify_buffer in-event <InotifyEvent: src_path=b'/home/webadmin/dmoj-docker/dmoj/problems/cypher/init.yml', wd=6, mask=IN_OPEN, cookie=0, name='init.yml'>
DEBUG 2024-11-20 09:14:37,536 12538 inotify_buffer in-event <InotifyEvent: src_path=b'/home/webadmin/dmoj-docker/dmoj/problems/cypher/init.yml', wd=6, mask=IN_CLOSE_NOWRITE, cookie=0, name='init.yml'>
DEBUG 2024-11-20 09:14:37,538 12538 packet Update problems
DEBUG 2024-11-20 09:14:37,539 12538 inotify_buffer in-event <InotifyEvent: src_path=b'/home/webadmin/dmoj-docker/dmoj/problems', wd=1, mask=IN_ISDIR|IN_OPEN, cookie=0, name=''>
DEBUG 2024-11-20 09:14:37,540 12538 inotify_buffer in-event <InotifyEvent: src_path=b'/home/webadmin/dmoj-docker/dmoj/problems', wd=1, mask=IN_CLOSE_NOWRITE|IN_ISDIR, cookie=0, name=''>
DEBUG 2024-11-20 09:14:37,540 12538 inotify_buffer in-event <InotifyEvent: src_path=b'/home/webadmin/dmoj-docker/dmoj/problems/cypher/cypher.zip', wd=6, mask=IN_OPEN, cookie=0, name='cypher.zip'>
DEBUG 2024-11-20 09:14:37,542 12538 packet Update problems
DEBUG 2024-11-20 09:14:37,544 12538 inotify_buffer in-event <InotifyEvent: src_path=b'/home/webadmin/dmoj-docker/dmoj/problems', wd=1, mask=IN_ISDIR|IN_OPEN, cookie=0, name=''>
DEBUG 2024-11-20 09:14:37,544 12538 inotify_buffer in-event <InotifyEvent: src_path=b'/home/webadmin/dmoj-docker/dmoj/problems', wd=1, mask=IN_CLOSE_NOWRITE|IN_ISDIR, cookie=0, name=''>
DEBUG 2024-11-20 09:14:37,568 13891 isolate Denied syscall access: Denying /etc/ld.so.preload, normalized to /etc/ld.so.preload
DEBUG 2024-11-20 09:14:37,590 13891 isolate Denied syscall fstatat: Denying /home/webadmin/.local/lib/python3.9/site-packages, normalized to /home/webadmin/.local/lib/python3.9/site-packages
DEBUG 2024-11-20 09:14:37,623 13891 isolate Denied syscall openat: Denying /opt/Python-3.9.0/Lib/__pycache__/compileall.cpython-39.pyc.22924333873840, normalized to /opt/Python-3.9.0/Lib/__pycache__/compileall.cpython-39.pyc.22924333873840
DEBUG 2024-11-20 09:14:37,628 13891 isolate Denied syscall openat: Denying /opt/Python-3.9.0/Lib/__pycache__/py_compile.cpython-39.pyc.22924332365616, normalized to /opt/Python-3.9.0/Lib/__pycache__/py_compile.cpython-39.pyc.22924332365616
DEBUG 2024-11-20 09:14:37,645 13891 isolate Denied syscall openat: Denying /opt/Python-3.9.0/Lib/__pycache__/filecmp.cpython-39.pyc.22924331950240, normalized to /opt/Python-3.9.0/Lib/__pycache__/filecmp.cpython-39.pyc.22924331950240
DEBUG 2024-11-20 09:14:37,659 13891 isolate Denied syscall openat: Denying /opt/Python-3.9.0/Lib/__pycache__/pathlib.cpython-39.pyc.22924331952592, normalized to /opt/Python-3.9.0/Lib/__pycache__/pathlib.cpython-39.pyc.22924331952592
DEBUG 2024-11-20 09:14:37,665 13891 isolate Denied syscall openat: Denying /opt/Python-3.9.0/Lib/__pycache__/ntpath.cpython-39.pyc.22924331951920, normalized to /opt/Python-3.9.0/Lib/__pycache__/ntpath.cpython-39.pyc.22924331951920
DEBUG 2024-11-20 09:14:37,668 13891 isolate Denied syscall mkdir: Denying /opt/Python-3.9.0/Lib/urllib/__pycache__, normalized to /opt/Python-3.9.0/Lib/urllib/__pycache__
DEBUG 2024-11-20 09:14:37,675 13891 isolate Denied syscall mkdir: Denying /opt/Python-3.9.0/Lib/urllib/__pycache__, normalized to /opt/Python-3.9.0/Lib/urllib/__pycache__
DEBUG 2024-11-20 09:14:37,702 12538 packet Compile message: 51
DEBUG 2024-11-20 09:14:37,703 12538 packet Begin grading: 51
DEBUG 2024-11-20 09:14:37,704 12538 packet Enter batch number 1: 51
INFO 2024-11-20 09:14:37,705 12538 judge Batch #1
DEBUG 2024-11-20 09:14:37,728 13891 isolate Denied syscall access: Denying /etc/ld.so.preload, normalized to /etc/ld.so.preload
DEBUG 2024-11-20 09:14:37,734 13891 isolate Denied syscall openat: Denying /usr/share/locale/locale.alias, real path /etc/locale.alias
INFO 2024-11-20 09:14:37,796 12538 judge   Test case  1 WA [0.050s (0.075s wall) | 9004kb | 371 switches (12 involuntary)] 
DEBUG 2024-11-20 09:14:37,797 12538 packet Test case on 51: #1, WA [0.050s | 8.79 MB], 0.0/15
DEBUG 2024-11-20 09:14:37,797 12538 packet Exit batch number 1: 51
DEBUG 2024-11-20 09:14:37,798 12538 packet End grading: 51
INFO 2024-11-20 09:14:37,799 12538 judge Done grading cypher/51.
```

**Comment by kiritofeng** [comment]
There's no built-in mechanism for this; if you want to check why the output and judge answer are a mismatch, you can implement a simple custom checker as follows:
```py
import sys
import difflib

from dmoj.checkers.standard import check as std_check


def check(process_output, judge_output, **kwargs):
    process_lines = list(filter(None, process_output.splitlines()))
    judge_lines = list(filter(None, judge_output.splitlines()))
    sys.stdout.writelines(unified_diff(judge_lines, process_lines, fromfile='answer', tofile='output', lineterm=''))

    return std_check(process_output, judge_output, **kwargs)
```

See [https://docs.dmoj.ca/#/problem_format/custom_checkers](https://docs.dmoj.ca/#/problem_format/custom_checkers) for docs on how to specify custom checkers.

(I make no claims of correctness nor efficiency of this code)

**Comment by xDololow** [comment]
Tried to run it, it gave me this:
```
ERROR 2024-11-21 02:52:27,441 55928 judge Traceback (most recent call last):
  File "/home/webadmin/dmoj-docker/dmoj/judge-server/dmoj/judge.py", line 415, in _worker_process_main
    ipc_msg = next(case_gen)
  File "/home/webadmin/dmoj-docker/dmoj/judge-server/dmoj/judge.py", line 506, in _grade_cases
    result = self.grader.grade(case)
  File "/home/webadmin/dmoj-docker/dmoj/judge-server/dmoj/graders/standard.py", line 31, in grade
    check = self.check_result(case, result)
  File "/home/webadmin/dmoj-docker/dmoj/judge-server/dmoj/graders/standard.py", line 59, in check_result
    check = checker(
  File "/home/webadmin/dmoj-docker/dmoj/judge-server/dmoj/checkers/testcheck.py", line 10, in check
    sys.stdout.writelines(unified_diff(judge_lines, process_lines, fromfile='answer', tofile='output', lineterm=''))
  File "/usr/lib/python3.10/codecs.py", line 385, in writelines
    self.write(''.join(list))
  File "/usr/lib/python3.10/difflib.py", line 1136, in unified_diff
    _check_types(a, b, fromfile, tofile, fromfiledate, tofiledate, lineterm)
  File "/usr/lib/python3.10/difflib.py", line 1264, in _check_types
    raise TypeError('lines to compare must be str, not %s (%r)' %
TypeError: lines to compare must be str, not bytes (b'012202000101001000200202')
```

**Comment by xDololow** [comment]
For some reason, process_lines have only one value and judge_lines have all of them.

![image](https://github.com/user-attachments/assets/e2c5fe2c-3992-451d-a12b-45e1feac74d8)

**Comment by xDololow** [comment]
> Did you put the outputs for all of the cases into a single answer file while splitting the inputs for each case separately?

I have one "in" and one "out" files.

**Comment by kiritofeng** [comment]
The input passed to your program is stored in `judge_input`. You can print that out, and compare the results of running your program on that.

I am unconvinced that this is a judge issue; it seems more likely that you've somehow misconfigured something. If you still think this is a bug with the judge itself, could you please post a minimal working example?
