### ISSUE TITLE
Monitor is unable to start after running judge in docker container

### ISSUE THREAD

**Issue by kartik-mathur-cb** [DMOJ/judge-server#1192]
ERROR 2024-12-16 11:17:50,629 7 monitor Failed to start problem monitor.
Traceback (most recent call last):
  File "/judge/dmoj/monitor.py", line 116, in start
    self._monitor.start()
  File "/env/lib/python3.12/site-packages/watchdog/observers/api.py", line 264, in start
    emitter.start()
  File "/env/lib/python3.12/site-packages/watchdog/utils/__init__.py", line 75, in start
    self.on_thread_start()
  File "/env/lib/python3.12/site-packages/watchdog/observers/inotify.py", line 119, in on_thread_start
    self._inotify = InotifyBuffer(path, recursive=self.watch.is_recursive, event_mask=event_mask)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/watchdog/observers/inotify_buffer.py", line 30, in __init__
    self._inotify = Inotify(path, recursive=recursive, event_mask=event_mask)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/watchdog/observers/inotify_c.py", line 187, in __init__
    self._add_watch(path, event_mask)
  File "/env/lib/python3.12/site-packages/watchdog/observers/inotify_c.py", line 424, in _add_watch
    Inotify._raise_error()
  File "/env/lib/python3.12/site-packages/watchdog/observers/inotify_c.py", line 441, in _raise_error
    raise OSError(err, os.strerror(err))
FileNotFoundError: [Errno 2] No such file or directory
Warning: failed to start problem monitor!

**Comment by kartik-mathur-cb** [comment]
I have verified the path under `problem_storage_globs` in `judge.yml` on my end.The problem is still persisting. Due to this error I am not able to find any judge under the `judge available` section of a problem even after it is recognised under judges in admin panel.

**Comment by magedmg** [comment]
Hi I am having the same issue, did you find a solution?

**Comment by devhoodit** [comment]
can you share your judge.yml? maybe problem_storage_globs value is wrong

**Comment by magedmg** [comment]
Yeah the problem_storage_globs value was wrong 👍
