### ISSUE TITLE
Compilation leaks pty descriptors

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge-server#593]
Eventually, all compilations fail with:

```python
Traceback (most recent call last):
 File "/judge/dmoj/judge.py", line 164, in grading_cleanup_wrapper
   self._block_and_grade(problem, language, source, short_circuit, meta, report=report)
 File "/judge/dmoj/judge.py", line 93, in _block_and_grade
   self.current_grader = grader_class(self, problem, language, utf8bytes(source), meta)
 File "/judge/dmoj/graders/base.py", line 13, in __init__
   self.binary = self._generate_binary()
 File "/judge/dmoj/graders/standard.py", line 137, in _generate_binary
   unbuffered=self.problem.config.unbuffered)
 File "/judge/dmoj/executors/compiled_executor.py", line 63, in __call__
   obj.compile()
 File "/judge/dmoj/executors/compiled_executor.py", line 216, in compile
   process = self.get_compile_process()
 File "/judge/dmoj/executors/compiled_executor.py", line 156, in get_compile_process
   self._master, self._slave = pty.openpty()
 File "/usr/lib/python3.7/pty.py", line 29, in openpty
   master_fd, slave_name = _open_terminal()
 File "/usr/lib/python3.7/pty.py", line 59, in _open_terminal
   raise OSError('out of pty devices')
OSError: out of pty devices
```

I believe we exacerbated this issue in https://github.com/DMOJ/judge-server/pull/579, even though it was always present for e.g. C++. The extra leaking may also explain the memory leaks experienced since 2.0.0.

**Comment by Xyene** [comment]
Closing, as this was found to be due to user error and not closing both ends of a pty in custom graders. It visibly affected compilation, but was not caused by it.
