### ISSUE TITLE
EOFError in judge controller during grading

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge-server#682]
```
INFO 2020-05-31 20:24:29,649 57 judge Start grading hopscotch2/1947240 in JAVA8...
INFO 2020-05-31 20:24:29,659 57 packet Accept submission: 1947240: executor: JAVA8, code: hopscotch2
INFO 2020-05-31 20:24:30,551 57 judge Batch #1
10.62.0.2 - - [31/May/2020 20:24:30] Problem update requested.
10.62.0.2 - - [31/May/2020 20:24:30] "POST /update/problems HTTP/1.1" 200 -
WARNING 2020-05-31 20:24:38,109 4176 tracer Shocker activated and killed 4204
ERROR 2020-05-31 20:24:38,720 57 judge Failed to read IPC message from handler!
Traceback (most recent call last):
  File "/judge/dmoj/judge.py", line 131, in _grading_thread_main
    for ipc_type, data in self.current_judge_worker.run():
  File "/judge/dmoj/judge.py", line 270, in run
    ipc_type, data = self.worker_process_conn.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

---

```
INFO 2020-05-31 16:29:43,644 56 judge Start grading hopscotch2/1947240 in JAVA8...
INFO 2020-05-31 16:29:43,658 56 packet Accept submission: 1947240: executor: JAVA8, code: hopscotch2
INFO 2020-05-31 16:29:44,595 56 judge Batch #1
WARNING 2020-05-31 16:29:51,965 30936 tracer Shocker activated and killed 30964
ERROR 2020-05-31 16:29:52,394 56 judge Failed to read IPC message from worker!
Traceback (most recent call last):
  File "/judge/dmoj/judge.py", line 148, in _grading_thread_main
    for ipc_type, data in self.current_judge_worker.communicate():
  File "/judge/dmoj/judge.py", line 290, in communicate
    ipc_type, data = self.worker_process_conn.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by Xyene** [comment]
```
INFO 2020-06-07 18:47:51,680 59 judge Start grading ccc96s2/2133397 in GAS64...
INFO 2020-06-07 18:47:51,691 59 packet Accept submission: 2133397: executor: GAS64, code: ccc96s2
INFO 2020-06-07 18:49:07,944 59 packet Received abortion request for 2133397
ERROR 2020-06-07 18:49:12,948 59 judge Worker is still alive, sending SIGKILL!
ERROR 2020-06-07 18:49:12,951 59 judge Failed to read IPC message from worker!
ERROR 2020-06-07 18:49:12,972 59 judge Traceback (most recent call last):
  File "/judge/dmoj/judge.py", line 148, in _grading_thread_main
    for ipc_type, data in self.current_judge_worker.communicate():
  File "/judge/dmoj/judge.py", line 292, in communicate
    ipc_type, data = self.worker_process_conn.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by Xyene** [comment]
Fixed in https://github.com/DMOJ/judge-server/commit/e1a9b23dec3bc2ae2b883b39c22986f9334044e8.
