### ISSUE TITLE
ptrace: Operation not permitted while building judge server docker image

### ISSUE THREAD

**Issue by hanasim** [DMOJ/judge-server#858]
I cloned and followed the steps as mentioned in the documentation. However, the `docker build` step fails with 'Operation not permitted'. Because of this `judge-runtime-paths.yml` is _not_ generated and I can't proceed to next steps.

```
$ git clone --recursive https://github.com/DMOJ/judge-server.git
$ cd judge-server/.docker
$ make judge-tier1
cd tier1 && docker build --build-arg TAG="master" -t dmoj/judge-tier1 -t dmoj/judge-tier1:latest .
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM dmoj/runtimes-tier1
 ---> 8d857c666f43
Step 2/4 : ARG TAG=master
 ---> Using cache
 ---> 72c34c140f02
Step 3/4 : RUN mkdir /judge /problems && cd /judge && 	curl -L https://github.com/DMOJ/judge-server/archive/"${TAG}".tar.gz | tar -xz --strip-components=1 && 	pip3 install -e . && 	. ~judge/.profile && 	runuser -u judge -w PATH -- dmoj-autoconf -V > /judge-runtime-paths.yml && 	echo '  crt_x86_in_lib32: true' >> /judge-runtime-paths.yml
 ---> Running in 76d63c11b0f6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125  100   125    0     0    748      0 --:--:-- --:--:-- --:--:--   748
100  799k    0  799k    0     0  1719k      0 --:--:-- --:--:-- --:--:-- 1719k
Obtaining file:///judge
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting pyyaml
  Downloading PyYAML-5.4.1-cp39-cp39-manylinux1_x86_64.whl (630 kB)
Collecting setproctitle
  Downloading setproctitle-1.2.2-cp39-cp39-manylinux1_x86_64.whl (35 kB)
Collecting pylru
  Downloading pylru-1.2.0.tar.gz (18 kB)
Collecting pygments
  Downloading Pygments-2.9.0-py3-none-any.whl (1.0 MB)
Collecting watchdog
  Downloading watchdog-2.1.1-py3-none-manylinux2014_x86_64.whl (74 kB)
Collecting termcolor
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
Building wheels for collected packages: pylru, termcolor
  Building wheel for pylru (setup.py): started
  Building wheel for pylru (setup.py): finished with status 'done'
  Created wheel for pylru: filename=pylru-1.2.0-py3-none-any.whl size=15691 sha256=801a577442f805b553ee83d1d73d056799cf9399222cff5008d9aaa94cf6b1fb
  Stored in directory: /root/.cache/pip/wheels/04/f4/30/a7c4d82b70acc60310d9ef4c1aeb9fb87b105a3cff1e418490
  Building wheel for termcolor (setup.py): started
  Building wheel for termcolor (setup.py): finished with status 'done'
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4830 sha256=cbed80ea0a2e0a3c9be04ab59cda5d90121adcdf343f089d38e325cba286e9f7
  Stored in directory: /root/.cache/pip/wheels/b6/0d/90/0d1bbd99855f99cb2f6c2e5ff96f8023fad8ec367695f7d72d
Successfully built pylru termcolor
Installing collected packages: watchdog, termcolor, setproctitle, pyyaml, pylru, pygments, dmoj
  Running setup.py develop for dmoj
Successfully installed dmoj pygments-2.9.0 pylru-1.2.0 pyyaml-5.4.1 setproctitle-1.2.2 termcolor-1.1.0 watchdog-2.1.1
Auto-configuring ADA:    Failed to find "gnatmake"
ptrace: Operation not permitted
Auto-configuring AWK:    Traceback (most recent call last):
  File "/judge/dmoj/cptbox/tracer.py", line 317, in _run_process
    oom_score_adj(OOM_SCORE_ADJ_MAX, self.pid)
  File "/judge/dmoj/utils/os_ext.py", line 19, in oom_score_adj
    with open('/proc/%s/oom_score_adj' % to, 'wb') as f:
PermissionError: [Errno 13] Permission denied: '/proc/106/oom_score_adj'
Failed self-test
  Attempted:
    awk: /usr/bin/mawk
  Errors:
    Traceback (most recent call last):
      File "/judge/dmoj/executors/base_executor.py", line 147, in run_self_test
        stdout, stderr = proc.communicate(test_message + b'\n')
      File "/judge/dmoj/utils/communicate.py", line 96, in safe_communicate
        proc.wait()
      File "/judge/dmoj/cptbox/tracer.py", line 193, in wait
        raise RuntimeError(
    RuntimeError: failed to ptrace child, check Yama config (https://www.kernel.org/doc/Documentation/security/Yama.txt, should be at most 1); if running in Docker, must run container with `--cap-add=SYS_PTRACE`
    
ptrace: Operation not permitted
...
...
```

**Comment by kiritofeng** [comment]
Can you provide more information on the system you're running this on? I spun up a clean Debian 10 droplet and was able to compete the build (for the latest commit) without issue.

**Comment by hanasim** [comment]
```
$ cat /etc/os-release 
NAME="Sangoma Linux"
VERSION="7 (Core)"
ID="sangoma"
ID_LIKE="centos rhel fedora"
VERSION_ID="7"
PRETTY_NAME="Sangoma Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:sangoma:sng:7::server:utf8"
HOME_URL="https://distro.sangoma.net/"
BUG_REPORT_URL="https://issues.sangoma.net/"

CENTOS_MANTISBT_PROJECT="Sangoma-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="sangoma"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

I checked the ptrace scope on this system.

```
$ cat /proc/sys/kernel/yama/ptrace_scope
0

$ sysctl kernel.yama.ptrace_scope
kernel.yama.ptrace_scope = 0
```

**Comment by quantum5** [comment]
The problem is that your kernel is too old, and Docker (<19.03) requires you to run with `--cap-add=SYS_PTRACE` on older kernels (<4.8). See https://jvns.ca/blog/2020/04/29/why-strace-doesnt-work-in-docker/ for details.

Unfortunately, since there is absolutely no way to run `docker build` with `--cap-add=SYS_PTRACE`, you are simply out of luck unless you upgrade kernel and docker. You could try building this on a different machine and use the image.

A long term solution would be to upload prebuilt judge images for stable releases, but that will take some time.

**Comment by hanasim** [comment]
Thank you for the response.

For the time being, I worked around the problem by building judge server image without the runtime file generation. Once it was built, I `docker run --cap-add=SYS_PTRACE <IMG> dmoj-conf` and copied it into another docker image.

Long term solution with prebuilt judge images would be fantastic!
