### ISSUE TITLE
judge submit

### ISSUE THREAD

**Issue by ak-soft** [DMOJ/judge-server#981]
I have run DMOJ site as docker composed container (besides Redis and MySql). I have install java8 on judge_base image and run it in a workstation. After submit a problem:

```
INFO 2022-01-02 06:13:32,870 1 monitor Scheduled for monitoring: /problems

Traceback (most recent call last):
  File "/judge/dmoj/packet.py", line 117, in _read_async
    self._receive_packet(self._read_single())
  File "/judge/dmoj/packet.py", line 179, in _receive_packet
    packet['pretests-only']
KeyError: 'pretests-only'
Traceback (most recent call last):
  File "/judge/dmoj/judge.py", line 402, in judge_proc
    judge.listen()
  File "/judge/dmoj/judge.py", line 297, in listen
    self.packet_manager.run()
  File "/judge/dmoj/packet.py", line 143, in run
    self._read_async()
  File "/judge/dmoj/packet.py", line 122, in _read_async
    raise SystemExit(1)
SystemExit: 1

```

**Comment by Xyene** [comment]
Your site/bridge install is much too old to run that version of the judge. Upgrading the site will fix this.

**Comment by ak-soft** [comment]
@Xyene These are bridge logs:
```
INFO 2022-01-05 03:17:30,470 judge_handler Judge connected from: ('172.22.0.5', 47184)
INFO 2022-01-05 03:17:30,486 judge_handler Judge authenticated: ('172.22.0.5', 47184) (judge1)
INFO 2022-01-05 03:19:49,414 judge_list Free judges: 1
INFO 2022-01-05 03:19:49,415 judge_list Dispatched submission 2 to: judge1
INFO 2022-01-05 03:19:49,455 judge_handler Submission acknowledged: 2
ERROR 2022-01-05 03:19:49,660 judge_handler Judge judge1 disconnected while handling submission 2
INFO 2022-01-05 03:19:49,722 judge_handler Judge disconnected from: ('172.22.0.5', 47184) with name judge1
ERROR 2022-01-05 03:19:49,730 judge_handler {"judge": "judge1", "address": "[172.22.0.5]:47184", "submission": 2, "action": "close", "info": "IE due to shutdown on grading"}
INFO 2022-01-05 03:19:54,276 judge_handler Judge connected from: ('172.22.0.5', 47274)
```

**Comment by ak-soft** [comment]
@Xyene 
same error with latest commit of master: https://github.com/DMOJ/site.git

```
commit 015d326796ef2d73d3a93eae8bb2efefe4b16454 (HEAD -> master, origin/master, origin/HEAD)
Author: Jason Yuen <jason_yuen2007@hotmail.com>
Date:   Thu Dec 30 20:53:45 2021 -0500

    Add space in rating chart (#1817)
    
    Good contest performance can result in +50, so let's set the spacing to this.
    
    Co-authored-by: Quantum <quantum2048@gmail.com>
```
